### ISSUE TITLE
ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'

### ISSUE THREAD

**Issue by tonyschuite** [WillCodeForCats/solaredge-modbus-multi#916]
### Describe the bug

After updating to 2025.10 I get the following error:

ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'

### Expected behavior

no data

### Diagnostic File

unable to get diagnostics.

### Debug logs

```shell

```

### Home Assistant Version

2025.10

### solaredge-modbus-multi Version

3.1.2

### Installation Type

HAOS

### Read the Instructions

- [x] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [x] I have read the Known Issues https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Known-Issues
- [x] This issue is not about a template error (do not report template errors, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)
